// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuM0A4hZVWPX9I-fJuHktxRDn5dHTTPgI',
    appId: '1:1033137996:web:1027b69122acbe6cb5a9e9',
    messagingSenderId: '1033137996',
    projectId: 'enad-movil',
    authDomain: 'enad-movil.firebaseapp.com',
    storageBucket: 'enad-movil.firebasestorage.app',
    measurementId: 'G-3NRY0525YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmbFyGHgBYO1vqdwDbTqXdotyXP6wtxwQ',
    appId: '1:1033137996:android:815ea64d63404354b5a9e9',
    messagingSenderId: '1033137996',
    projectId: 'enad-movil',
    storageBucket: 'enad-movil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEd-WOMU6cq_07SurFzxE81BHz05cXjS4',
    appId: '1:1033137996:ios:94e4a8c3b273aba7b5a9e9',
    messagingSenderId: '1033137996',
    projectId: 'enad-movil',
    storageBucket: 'enad-movil.firebasestorage.app',
    iosClientId: '1033137996-0q8vct49sl1atq5tgeo3o37ih9jsmcl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontEndFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEd-WOMU6cq_07SurFzxE81BHz05cXjS4',
    appId: '1:1033137996:ios:94e4a8c3b273aba7b5a9e9',
    messagingSenderId: '1033137996',
    projectId: 'enad-movil',
    storageBucket: 'enad-movil.firebasestorage.app',
    iosClientId: '1033137996-0q8vct49sl1atq5tgeo3o37ih9jsmcl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontEndFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuM0A4hZVWPX9I-fJuHktxRDn5dHTTPgI',
    appId: '1:1033137996:web:600afafeb98cbc2fb5a9e9',
    messagingSenderId: '1033137996',
    projectId: 'enad-movil',
    authDomain: 'enad-movil.firebaseapp.com',
    storageBucket: 'enad-movil.firebasestorage.app',
    measurementId: 'G-YZMWECSYBS',
  );
}
